import path from 'path';
import MarkdownIt from 'markdown-it';
import { logger } from '../utils/logger.js';
import { writeFile, ensureDir } from '../utils/file-utils.js';
import { ExecutionContext, WorkflowResult } from '../core/types.js';

const md = new MarkdownIt();

/**
 * Generates markdown reports for each workflow phase
 */
export class ReportGenerator {
  /**
   * Generate phase 0 setup report
   */
  async generateSetupReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating setup report`);

    const reportPath = path.join(context.workingDir, 'task-automation-setup-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Setup Report
> Generated: ${timestamp}

## Task Information
- **Task ID**: ${context.task.taskId}
- **Title**: ${context.task.title}
- **Description**: ${context.task.description}
- **Estimated Points**: ${context.task.estimatedPoints}

## Setup Details
- **Branch**: ${context.branchName}
- **Project Path**: ${context.workingDir}
- **Status**: SETUP_COMPLETE

## Acceptance Criteria
${context.task.acceptanceCriteria.map((c) => `- [ ] ${c}`).join('\n')}

## Next Steps
1. Phase 1: Project Analysis (xray + testlens)
2. Phase 2: Extract Patterns
3. Phase 3: Implementation
4. Phase 4: Testing
5. Phase 5: Code Review
6. Phase 6: Validation
7. Phase 7: Finalization

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Setup report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate phase 1 analysis report
   */
  async generateAnalysisReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating analysis report`);

    if (!context.projectAnalysis) {
      throw new Error('Project analysis required');
    }

    const reportPath = path.join(context.workingDir, 'task-automation-analysis-report.md');
    const timestamp = new Date().toISOString();
    const analysis = context.projectAnalysis;

    const content = `# Task Automation - Analysis Report
> Generated: ${timestamp}

## Project Analysis

### Detected Stack
- **Language**: ${analysis.language}
- **Build Tool**: ${analysis.buildTool}
- **Framework**: ${analysis.framework}
- **Test Framework**: ${analysis.testFramework}

### Architecture
\`\`\`
${analysis.architecture}
\`\`\`

### Components
${analysis.components.length > 0 ? analysis.components.map((c) => `- ${c}`).join('\n') : '- None detected yet'}

### Dependencies
${
  analysis.dependencies.length > 0
    ? analysis.dependencies
        .map((d) => `- ${d.name}@${d.version} (scope: ${d.scope}, fixed: ${d.fixed})`)
        .join('\n')
    : '- None detected yet'
}

## XRay Report
${analysis.xrayReportPath ? `Generated: ${analysis.xrayReportPath}` : 'Pending generation'}

## Next Phase
Extract test patterns and code style conventions

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Analysis report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate phase 2 patterns report
   */
  async generatePatternsReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating patterns report`);

    if (!context.testPatterns) {
      throw new Error('Test patterns analysis required');
    }

    const reportPath = path.join(context.workingDir, 'task-automation-patterns-report.md');
    const timestamp = new Date().toISOString();
    const patterns = context.testPatterns;

    const content = `# Task Automation - Patterns Report
> Generated: ${timestamp}

## Test Patterns Detected

### Framework Information
- **Test Framework**: ${patterns.framework}
- **Framework Version**: ${patterns.frameworkVersion}
- **Mocking Library**: ${patterns.mockingLibrary}
- **Assertion Library**: ${patterns.assertionLibrary}

### Naming Conventions
- **Test File Pattern**: ${patterns.namingConvention}
- **Integration Test Pattern**: ${patterns.integrationTestPattern || 'Not detected'}

### Coverage Baseline
- **Current Coverage**: ${patterns.coverageBaseline}%
- **Target Coverage**: 70%

## Code Style Patterns

${context.codeStylePatterns ? this.formatCodeStylePatterns(context.codeStylePatterns) : '- Not analyzed yet'}

## Next Phase
Implement feature based on extracted patterns

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Patterns report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate execution summary
   */
  async generateExecutionSummary(context: ExecutionContext): Promise<string> {
    logger.info(`Generating execution summary`);

    const reportPath = path.join(context.workingDir, 'task-automation-summary.md');
    const timestamp = new Date().toISOString();

    let phasesContent = '';
    let totalDuration = 0;

    context.phaseResults.forEach((result, phase) => {
      totalDuration += result.duration;
      phasesContent += `### Phase ${phase}: ${result.status}
- Duration: ${result.duration}ms
- Message: ${result.message}
${result.errors ? `- Errors:\n${result.errors.map((e) => `  - ${e}`).join('\n')}` : ''}

`;
    });

    const content = `# Task Automation - Execution Summary
> Generated: ${timestamp}

## Overview
- **Task**: ${context.task.taskId} - ${context.task.title}
- **Branch**: ${context.branchName}
- **Total Duration**: ${totalDuration}ms (~${(totalDuration / 1000 / 60).toFixed(1)} minutes)

## Phase Results

${phasesContent}

## Generated Reports
${Array.from(context.reports.entries())
  .map(([name, path]) => `- ${name}: ${path}`)
  .join('\n')}

## Status
✅ Analysis phase complete. Ready for implementation phase.

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Summary saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Format code style patterns
   */
  private formatCodeStylePatterns(patterns: any): string {
    let content = '### Naming Conventions\n';
    for (const [key, value] of Object.entries(patterns.namingConventions || {})) {
      content += `- ${key}: ${value}\n`;
    }

    content += `\n### Package Structure\n${patterns.packageStructure}\n`;
    content += `\n### Code Style\n`;
    content += `- Indentation: ${patterns.indentation}\n`;
    content += `- Line Length: ${patterns.lineLength}\n`;
    content += `- Documentation Style: ${patterns.docstringStyle}\n`;

    return content;
  }
}

export default new ReportGenerator();
