import path from 'path';
import MarkdownIt from 'markdown-it';
import { logger } from '../utils/logger.js';
import { writeFile, ensureDir } from '../utils/file-utils.js';
import { ExecutionContext, WorkflowResult, ValidationResult } from '../core/types.js';

const md = new MarkdownIt();

/**
 * Generates markdown reports for each workflow phase
 */
export class ReportGenerator {
  /**
   * Generate phase 0 setup report
   */
  async generateSetupReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating setup report`);

    const reportPath = path.join(context.workingDir, 'task-automation-setup-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Setup Report
> Generated: ${timestamp}

## Task Information
- **Task ID**: ${context.task.taskId}
- **Title**: ${context.task.title}
- **Description**: ${context.task.description}
- **Estimated Points**: ${context.task.estimatedPoints}

## Setup Details
- **Branch**: ${context.branchName}
- **Project Path**: ${context.workingDir}
- **Status**: SETUP_COMPLETE

## Acceptance Criteria
${context.task.acceptanceCriteria.map((c) => `- [ ] ${c}`).join('\n')}

## Next Steps
1. Phase 1: Project Analysis (xray + testlens)
2. Phase 2: Extract Patterns
3. Phase 3: Implementation
4. Phase 4: Testing
5. Phase 5: Code Review
6. Phase 6: Validation
7. Phase 7: Finalization

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Setup report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate phase 1 analysis report
   */
  async generateAnalysisReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating analysis report`);

    if (!context.projectAnalysis) {
      throw new Error('Project analysis required');
    }

    const reportPath = path.join(context.workingDir, 'task-automation-analysis-report.md');
    const timestamp = new Date().toISOString();
    const analysis = context.projectAnalysis;

    const content = `# Task Automation - Analysis Report
> Generated: ${timestamp}

## Project Analysis

### Detected Stack
- **Language**: ${analysis.language}
- **Build Tool**: ${analysis.buildTool}
- **Framework**: ${analysis.framework}
- **Test Framework**: ${analysis.testFramework}

### Architecture
\`\`\`
${analysis.architecture}
\`\`\`

### Components
${analysis.components.length > 0 ? analysis.components.map((c) => `- ${c}`).join('\n') : '- None detected yet'}

### Dependencies
${
  analysis.dependencies.length > 0
    ? analysis.dependencies
        .map((d) => `- ${d.name}@${d.version} (scope: ${d.scope}, fixed: ${d.fixed})`)
        .join('\n')
    : '- None detected yet'
}

## XRay Report
${analysis.xrayReportPath ? `Generated: ${analysis.xrayReportPath}` : 'Pending generation'}

## Next Phase
Extract test patterns and code style conventions

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Analysis report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate phase 2 patterns report
   */
  async generatePatternsReport(context: ExecutionContext): Promise<string> {
    logger.info(`Generating patterns report`);

    if (!context.testPatterns) {
      throw new Error('Test patterns analysis required');
    }

    const reportPath = path.join(context.workingDir, 'task-automation-patterns-report.md');
    const timestamp = new Date().toISOString();
    const patterns = context.testPatterns;

    const content = `# Task Automation - Patterns Report
> Generated: ${timestamp}

## Test Patterns Detected

### Framework Information
- **Test Framework**: ${patterns.framework}
- **Framework Version**: ${patterns.frameworkVersion}
- **Mocking Library**: ${patterns.mockingLibrary}
- **Assertion Library**: ${patterns.assertionLibrary}

### Naming Conventions
- **Test File Pattern**: ${patterns.namingConvention}
- **Integration Test Pattern**: ${patterns.integrationTestPattern || 'Not detected'}

### Coverage Baseline
- **Current Coverage**: ${patterns.coverageBaseline}%
- **Target Coverage**: 70%

## Code Style Patterns

${context.codeStylePatterns ? this.formatCodeStylePatterns(context.codeStylePatterns) : '- Not analyzed yet'}

## Next Phase
Implement feature based on extracted patterns

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Patterns report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate validation report for Phase 3-6
   */
  async generateValidationReport(
    context: ExecutionContext,
    phase: number,
    result: ValidationResult
  ): Promise<string> {
    logger.info(`Generating validation report for Phase ${phase}`);

    const reportPath = path.join(
      context.workingDir,
      `task-automation-validation-phase${phase}-report.md`
    );
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Phase ${phase} Validation Report
> Generated: ${timestamp}

## ${result.phase} Validation

### Status
- **Result**: ${result.success ? '✅ PASSED' : '❌ FAILED'}
- **Duration**: ${result.duration}ms
- **Errors**: ${result.errors.length}
- **Warnings**: ${result.warnings.length}

### Errors
${
  result.errors.length > 0
    ? result.errors.map((e) => `- ${e}`).join('\n')
    : 'No errors detected'
}

### Warnings
${
  result.warnings.length > 0
    ? result.warnings.map((w) => `- ${w}`).join('\n')
    : 'No warnings detected'
}

### Details
${Object.entries(result.details)
  .map(([key, value]) => `- **${key}**: ${value}`)
  .join('\n')}

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Validation report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate code review report
   */
  async generateCodeReviewReport(context: ExecutionContext, issues: any[]): Promise<string> {
    logger.info(`Generating code review report`);

    const reportPath = path.join(context.workingDir, 'task-automation-code-review-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Code Review Report
> Generated: ${timestamp}

## Code Review Summary
- **Total Issues**: ${issues.length}
- **CRITICAL**: ${issues.filter((i) => i.severity === 'CRITICAL').length}
- **HIGH**: ${issues.filter((i) => i.severity === 'HIGH').length}
- **MEDIUM**: ${issues.filter((i) => i.severity === 'MEDIUM').length}
- **LOW**: ${issues.filter((i) => i.severity === 'LOW').length}

## Issues Detected

${
  issues.length > 0
    ? issues
        .map(
          (issue) =>
            `### ${issue.severity} - ${issue.category}
${issue.file ? `- **File**: ${issue.file}` : ''}
${issue.line ? `- **Line**: ${issue.line}` : ''}
- **Message**: ${issue.message}
${issue.suggestion ? `- **Suggestion**: ${issue.suggestion}` : ''}
`
        )
        .join('\n')
    : '✅ No code review issues detected'
}

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Code review report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate security review report
   */
  async generateSecurityReport(context: ExecutionContext, findings: any[]): Promise<string> {
    logger.info(`Generating security report`);

    const reportPath = path.join(context.workingDir, 'task-automation-security-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Security Review Report
> Generated: ${timestamp}

## Security Summary
- **Total Findings**: ${findings.length}
- **CRITICAL**: ${findings.filter((f) => f.severity === 'CRITICAL').length}
- **HIGH**: ${findings.filter((f) => f.severity === 'HIGH').length}
- **MEDIUM**: ${findings.filter((f) => f.severity === 'MEDIUM').length}
- **LOW**: ${findings.filter((f) => f.severity === 'LOW').length}

## Security Findings

${
  findings.length > 0
    ? findings
        .sort((a, b) => {
          const severityOrder = { CRITICAL: 0, HIGH: 1, MEDIUM: 2, LOW: 3 };
          return severityOrder[a.severity as keyof typeof severityOrder] - severityOrder[b.severity as keyof typeof severityOrder];
        })
        .map(
          (finding) =>
            `### ${finding.severity} - ${finding.category}
${finding.file ? `- **File**: ${finding.file}` : ''}
${finding.line ? `- **Line**: ${finding.line}` : ''}
${finding.owasp ? `- **OWASP**: ${finding.owasp}` : ''}
- **Description**: ${finding.description}
- **Remediation**: ${finding.remediation}
`
        )
        .join('\n')
    : '✅ No security findings detected'
}

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Security report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate performance review report
   */
  async generatePerformanceReport(context: ExecutionContext, issues: any[]): Promise<string> {
    logger.info(`Generating performance report`);

    const reportPath = path.join(context.workingDir, 'task-automation-performance-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Performance Review Report
> Generated: ${timestamp}

## Performance Summary
- **Total Issues**: ${issues.length}
- **HIGH Impact**: ${issues.filter((i) => i.severity === 'HIGH').length}
- **MEDIUM Impact**: ${issues.filter((i) => i.severity === 'MEDIUM').length}
- **LOW Impact**: ${issues.filter((i) => i.severity === 'LOW').length}

## Performance Issues

${
  issues.length > 0
    ? issues
        .sort((a, b) => {
          const severityOrder = { HIGH: 0, MEDIUM: 1, LOW: 2 };
          return severityOrder[a.severity as keyof typeof severityOrder] - severityOrder[b.severity as keyof typeof severityOrder];
        })
        .map(
          (issue) =>
            `### ${issue.severity} Impact - ${issue.category}
${issue.file ? `- **File**: ${issue.file}` : ''}
${issue.line ? `- **Line**: ${issue.line}` : ''}
- **Message**: ${issue.message}
- **Impact**: ${issue.impact}
- **Optimization**: ${issue.optimization}
`
        )
        .join('\n')
    : '✅ No performance issues detected'
}

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Performance report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate execution summary
   */
  async generateExecutionSummary(context: ExecutionContext): Promise<string> {
    logger.info(`Generating execution summary`);

    const reportPath = path.join(context.workingDir, 'task-automation-summary.md');
    const timestamp = new Date().toISOString();

    let phasesContent = '';
    let totalDuration = 0;

    context.phaseResults.forEach((result, phase) => {
      totalDuration += result.duration;
      phasesContent += `### Phase ${phase}: ${result.status}
- Duration: ${result.duration}ms
- Message: ${result.message}
${result.errors ? `- Errors:\n${result.errors.map((e) => `  - ${e}`).join('\n')}` : ''}

`;
    });

    const content = `# Task Automation - Execution Summary
> Generated: ${timestamp}

## Overview
- **Task**: ${context.task.taskId} - ${context.task.title}
- **Branch**: ${context.branchName}
- **Total Duration**: ${totalDuration}ms (~${(totalDuration / 1000 / 60).toFixed(1)} minutes)

## Phase Results

${phasesContent}

## Generated Reports
${Array.from(context.reports.entries())
  .map(([name, path]) => `- ${name}: ${path}`)
  .join('\n')}

## Status
✅ Analysis and validation phase complete. Ready for implementation phase.

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Summary saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Format code style patterns
   */
  private formatCodeStylePatterns(patterns: any): string {
    let content = '### Naming Conventions\n';
    for (const [key, value] of Object.entries(patterns.namingConventions || {})) {
      content += `- ${key}: ${value}\n`;
    }

    content += `\n### Package Structure\n${patterns.packageStructure}\n`;
    content += `\n### Code Style\n`;
    content += `- Indentation: ${patterns.indentation}\n`;
    content += `- Line Length: ${patterns.lineLength}\n`;
    content += `- Documentation Style: ${patterns.docstringStyle}\n`;

    return content;
  }

  /**
   * Generate Phase 3 implementation report
   */
  async generateImplementationReport(
    context: ExecutionContext,
    result: WorkflowResult
  ): Promise<string> {
    logger.info(`Generating implementation report`);

    const reportPath = path.join(
      context.workingDir,
      'task-automation-implementation-report.md'
    );
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Phase 3 Implementation Report
> Generated: ${timestamp}

## Implementation Summary
- **Task**: ${context.task.taskId} - ${context.task.title}
- **Status**: ${result.status}
- **Duration**: ${result.duration}ms (~${(result.duration / 1000).toFixed(1)}s)

## Feature Implementation

### Task Requirements
${context.task.acceptanceCriteria.map(c => `- [ ] ${c}`).join('\n')}

### Implementation Details
${result.data?.generatedCodePath ? `Generated code saved to: ${result.data.generatedCodePath}` : 'No code generated'}

### Agent Metrics
${
  result.data?.agentResponse ? `- Agent Duration: ${(result.data.agentResponse as any).duration}ms
- Tokens Used: ${(result.data.agentResponse as any).tokensUsed || 'N/A'}` : '- No agent metrics available'
}

## Build Validation
- **Result**: ${result.data?.buildValidation || 'UNKNOWN'}
- **Errors**: ${result.errors && result.errors.length > 0 ? result.errors.join('\n') : 'None'}

## Artifacts Generated
${result.data?.generatedCodePath ? `- Code Report: ${result.data.generatedCodePath}` : ''}

## Next Steps
1. Review generated code
2. Apply changes to project source files
3. Run full test suite
4. Execute Phase 4: Testing workflow

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Implementation report saved: ${reportPath}`);

    return reportPath;
  }

  /**
   * Generate Phase 4 testing report
   */
  async generateTestingReport(context: ExecutionContext, result: WorkflowResult): Promise<string> {
    logger.info(`Generating testing report`);

    const reportPath = path.join(context.workingDir, 'task-automation-testing-report.md');
    const timestamp = new Date().toISOString();

    const content = `# Task Automation - Phase 4 Testing Report
> Generated: ${timestamp}

## Testing Summary
- **Task**: ${context.task.taskId} - ${context.task.title}
- **Status**: ${result.status}
- **Duration**: ${result.duration}ms (~${(result.duration / 1000).toFixed(1)}s)

## Test Implementation

### Coverage Target
- **Baseline**: ${context.testPatterns?.coverageBaseline || 70}%
- **Target**: 70%+
- **Test Framework**: ${context.testPatterns?.framework || 'Unknown'}
- **Mocking Library**: ${context.testPatterns?.mockingLibrary || 'Unknown'}

### Test Execution
- **Result**: ${result.data?.testExecution || 'UNKNOWN'}
- **Generated Tests**: ${result.data?.generatedTestsPath || 'No tests generated'}

### Coverage Validation
- **Result**: ${result.data?.coverageValidation || 'UNKNOWN'}
- **Actual Coverage**: ${result.data?.coverage ? result.data.coverage + '%' : 'Unknown'}

## Errors
${result.errors && result.errors.length > 0 ? result.errors.map(e => `- ${e}`).join('\n') : 'No errors'}

## Artifacts Generated
${result.data?.generatedTestsPath ? `- Tests Report: ${result.data.generatedTestsPath}` : ''}

## Next Steps
1. Review generated tests
2. Apply changes to test files
3. Address any failing tests
4. Verify coverage meets or exceeds target
5. Execute Phase 5: Code Review workflow

---
Generated by Task Automation Engine
`;

    await writeFile(reportPath, content);
    logger.info(`Testing report saved: ${reportPath}`);

    return reportPath;
  }
}

export default new ReportGenerator();
